apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
